name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o instapaper-to-exist-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o instapaper-to-exist-linux-arm64 .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            instapaper-to-exist-linux-amd64
            instapaper-to-exist-linux-arm64
